spring:
  datasource:
    url: jdbc:mysql://mysql:3306/sandbox
    username: mysql_user
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  sql:
   init:
     mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update